04-01
js-tasks-ru/vue-20211116_khf116 pull request #8
Opened 2021-11-30 11:35 UTC by legionvitt

исправил названия вычисляемых свойств в 02-05 (MeetupAgenda)
добавил решение задания 04-01 (UiFormGroup)

2021-11-30 11:36 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-12-01 02:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-12-01 21:14 UTC, ShGKme requested changes
В 02-TheToaster требуется убрать реализацию фильтрации шаблоном из компонента со списком тостов. В остальном задачи приняты, но есть места, которые можно поправить.

2021-12-01 21:14 UTC, ShGKme commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +  <div class="form-group" :class="[inline ? 'form-group_inline' : '']">
Массив при привязке классов нужен, когда привязывается несколько классов или классов и объектов.

2021-12-01 21:14 UTC, ShGKme commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +  <div class="form-group" :class="[inline ? 'form-group_inline' : '']">
Во Vue, когда требуется добавить класс по условию, удобно использовать синтаксис привязки класса объектом, где ключ - имя класса, а значение - булево значение, которое обозначает, что класс требуется добавить.

[https://v3.vuejs.org/guide/class-and-style.html#object-syntax](https://v3.vuejs.org/guide/class-and-style.html#object-syntax)

Так явно видно, от чего зависит наличие какого класса, в привычном для Vue разработчиков стиле и удобно добавлять новые классы.

2021-12-01 21:14 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +        id: id,
Вместо `this.toasts.length` в качестве ключа лучше использовать или простой автоинкремент (`lastId++`), или случайное значение. В текущей реализации количество также работает, как автоинкремент, но это не гарантируется "самой сутью количества элементов в массиве".

Количество показываемых на данный момент тостов может ен быть идентификатором конкретного тоста. Например, можно всегда добавлять тосты в такой момент времени, чтобы их количество было постоянным. Если в будущем тосты из массива будут удаляться (в новом решении, например), то появится проблема с ключом.

2021-12-01 21:14 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +};
👍

2021-12-01 21:14 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  },
`item` не самое удачное название для параметра, который определяет, какой именно тост будет выводиться. "Что такое `item у тоста`?"

2021-12-01 21:14 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToastList.vue
> +  </div>
`<span>` здесь лишний в разметке и добавлен только для работы цикла `v-for`. В таких ситуациях можно использовать элемент `<template>`, который также позволит повесить `v-for` или `v-if`, но не будет создавать лишней разметки.

2021-12-01 21:14 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToastList.vue
> +  </div>
Сейчас вывод только текущих тостов реализован фильтрацией внутри шаблона. Это и концептуально не очень хорошо (шаблон реализует логику работы компонента - фильтрацию), и технически (при каждом рендеринге будет проход по всему списку с проверкой каждого тоста).

Лучше как минимум использовать для этого вычисляемые свойства.

2021-12-01 21:14 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToastList.vue
> +  </div>
В целом решение, когда все тосты хранятся в массиве вечно, и лишь меняется флаг отображения - не лучшее решение для этой задачи. Каждый тост нужен всего на 5 секунд. Обычно они не показываются, не нужно показывать скрытые и т.д. В итоге в приложении всегда будет храниться вся длинная история тостов с их перебором для вывода тех не многих, которые нужны в текущие секунды.

2021-12-02 04:36 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-12-02 04:37 UTC, legionvitt commented
исправил моменты обозначенные в предыдущем PR
добавил решение задачи 04-03-UiDropdown1

2021-12-02 21:18 UTC, ShGKme requested changes
Всё ок, но в `03-UiDropdown1` опять встречается использование тернарника с пустой строкой вместо специальной возможности во Vue для этой задачи.

Поэтому попрошу это поправить, чтобы PR был принят.

2021-12-02 21:18 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToastList.vue
> +    </template>
`<template>` здесь не нужен, `v-for` можно установить сразу на тост

2021-12-02 21:18 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +      </template>
Аналогично лишний `<template>`

2021-12-02 21:18 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
Поиск выбранного варианта с перебором `options` через `this.options.find`  встречается в 2х вычисляемых свойствах. Вместо его вычисления трижды можно добавить отдельное вычисляемое свойство с этим же вычислением.

2021-12-02 21:18 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
Можно использовать метод `some`: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2021-12-02 21:18 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
Сейчас, смотря в шаблон, сложно узнать, какие же будут классы и когда использоваться в вёрстке. Требуется опуститься на почти 100 строк вниз, чтобы найти соответствующие вычисляемые свойства с тернарниками.

2021-12-02 21:18 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
В тоже время во Vue для таких случаев есть специальный инструмент - возможность привязывать классы по условиям через привязку объекта в `class`. Эта возможность есть во Vue именно потому, что часто требуется в приложениях добавлять классы по условиям, и использование этой возможности - более естественное решение для Vue компонента.

2021-12-02 22:28 UTC, legionvitt commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
да, согласен, не подумал сразу

2021-12-02 22:49 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-12-02 22:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-12-03 08:40 UTC, ShGKme approved these changes
Принято 👍

2021-12-03 08:41 UTC, merged